version: '3.4'
services:
  jenkins:
    build: .
    image: ragedunicorn/jenkins:1.0.2-dev
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080:8080"
    expose:
      - "50000"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.jenkins.environment: "dev"
      com.ragedunicorn.jenkins.description: "Jenkins"
volumes:
  jenkins_data: {}
