version: '3.6'
services:
  jenkins:
    build: .
    image: ragedunicorn/jenkins:1.0.2-stable
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080:8080"
    expose:
      - "50000"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.jenkins.environment: "prod"
      com.ragedunicorn.jenkins.description: "Jenkins"
volumes:
  jenkins_data: {}
